# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Runner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  config.build_settings['SWIFT_VERSION'] = '4.2'


  # Pods for Runner

end
